--- #YAML:1.0
name:                Tk-GridColumns
version:             0.05
abstract:            Columns widget for Tk
license:             ~
author:              
    - Matthias Wienand <matthias.wienand@googlemail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Tk:                            804
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
