--- #YAML:1.0
name:               Tk-GridColumns
version:            0.15
abstract:           Columns widget for Tk using Tk::grid
author:
    - Matthias Wienand <matthias.wienand@googlemail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tk:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
